# Generated by Django 4.2.8 on 2024-10-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('UNDELIVERED', 'Undelivered'), ('EXPIRED', 'Expired')], max_length=12)),
                ('statusdate', models.DateTimeField(blank=True, default=None, null=True)),
                ('partinfo', models.CharField(max_length=25)),
            ],
        ),
    ]
