import streamlit as st
from __init__ import custom_circle_plot
# from custom_circle_plot import custom_circle_plot

st.set_page_config(layout="wide")

data = [{"hero":"Alucard","Base Damage":97.68,"Unique Damage":2.32,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Fighter"},{"hero":"Alucard","Base Damage":97.68,"Unique Damage":2.32,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Assassin"},{"hero":"Balmond","Base Damage":100,"Unique Damage":0,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Fighter"},{"hero":"Zilong","Base Damage":81.37,"Unique Damage":18.63,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Fighter"},{"hero":"Zilong","Base Damage":81.37,"Unique Damage":18.63,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Assassin"},{"hero":"Chou","Base Damage":85.09,"Unique Damage":14.91,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Fighter"},{"hero":"Ruby","Base Damage":56.53,"Unique Damage":43.47,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Fighter"},{"hero":"Jawhead","Base Damage":92.72,"Unique Damage":0,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":7.28,"segment":"Fighter"},{"hero":"Martis","Base Damage":67.78,"Unique Damage":0,"Extra Damage":13.83,"Sustained Damage":0,"Passive Damage":18.4,"segment":"Fighter"},{"hero":"Dyrroth","Base Damage":57.43,"Unique Damage":0,"Extra Damage":19.14,"Sustained Damage":0,"Passive Damage":23.42,"segment":"Fighter"},{"hero":"Masha","Base Damage":100,"Unique Damage":0,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Fighter"},{"hero":"Masha","Base Damage":100,"Unique Damage":0,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Tank"},{"hero":"Argus","Base Damage":77.3,"Unique Damage":0,"Extra Damage":22.7,"Sustained Damage":0,"Passive Damage":0,"segment":"Fighter"},{"hero":"Phoveus","Base Damage":84.21,"Unique Damage":15.79,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Fighter"},{"hero":"Arlott","Base Damage":100,"Unique Damage":0,"Extra Damage":0,"Sustained Damage":0,"Passive Damage":0,"segment":"Fighter"}]
data_2 = [{'hero': 'Guinevere',
  'Base Damage': 75.6,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 6.85,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 10.52,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 7.03,
  'Passive Attribute Damage': 0.0,
  'segment': 'Fighter'},
 {'hero': 'Aulus',
  'Base Damage': 10.25,
  'Base Attribute Damage': 14.17,
  'Unique Damage': 31.63,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 43.95,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Fighter'},
 {'hero': 'Harley',
  'Base Damage': 90.0,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 0.0,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 2.69,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 7.31,
  'Passive Attribute Damage': 0.0,
  'segment': 'Assassin'},
 {'hero': 'Harley',
  'Base Damage': 90.0,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 0.0,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 2.69,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 7.31,
  'Passive Attribute Damage': 0.0,
  'segment': 'Mage'},
 {'hero': 'Lylia',
  'Base Damage': 80.65,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 19.35,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Mage'},
 {'hero': 'Badang',
  'Base Damage': 39.99,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 10.07,
  'Unique Attribute Damage': 48.13,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 1.81,
  'Passive Attribute Damage': 0.0,
  'segment': 'Fighter'},
 {'hero': 'Saber',
  'Base Damage': 29.23,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 4.57,
  'Unique Attribute Damage': 10.8,
  'Extra Damage': 55.4,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Assassin'},
 {'hero': 'Paquito',
  'Base Damage': 0.0,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 23.43,
  'Unique Attribute Damage': 16.49,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 35.87,
  'Passive Attribute Damage': 24.21,
  'segment': 'Fighter'},
 {'hero': 'Paquito',
  'Base Damage': 0.0,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 23.43,
  'Unique Attribute Damage': 16.49,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 35.87,
  'Passive Attribute Damage': 24.21,
  'segment': 'Assassin'},
 {'hero': 'Aurora',
  'Base Damage': 51.46,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 31.45,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 17.09,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Mage'},
 {'hero': 'Gord',
  'Base Damage': 12.61,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 66.58,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 20.81,
  'Passive Attribute Damage': 0.0,
  'segment': 'Mage'},
 {'hero': 'Chou',
  'Base Damage': 55.54,
  'Base Attribute Damage': 29.55,
  'Unique Damage': 14.91,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Fighter'},
 {'hero': 'Fanny',
  'Base Damage': 66.94,
  'Base Attribute Damage': 20.99,
  'Unique Damage': 0.0,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 9.98,
  'Passive Attribute Damage': 2.08,
  'segment': 'Assassin'},
 {'hero': 'Minsitthar',
  'Base Damage': 32.74,
  'Base Attribute Damage': 26.83,
  'Unique Damage': 0.0,
  'Unique Attribute Damage': 40.43,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Fighter'},
 {'hero': 'Pharsa',
  'Base Damage': 100.0,
  'Base Attribute Damage': 0.0,
  'Unique Damage': 0.0,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Mage'},
 {'hero': 'Natalia',
  'Base Damage': 60.99,
  'Base Attribute Damage': 20.95,
  'Unique Damage': 0.0,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 8.46,
  'Passive Attribute Damage': 9.6,
  'segment': 'Assassin'},
 {'hero': 'Fredrinn',
  'Base Damage': 59.82,
  'Base Attribute Damage': 21.24,
  'Unique Damage': 6.53,
  'Unique Attribute Damage': 12.42,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Fighter'},
 {'hero': 'Fredrinn',
  'Base Damage': 59.82,
  'Base Attribute Damage': 21.24,
  'Unique Damage': 6.53,
  'Unique Attribute Damage': 12.42,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Tank'},
 {'hero': 'Harith',
  'Base Damage': 39.81,
  'Base Attribute Damage': 12.09,
  'Unique Damage': 48.09,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Mage'},
 {'hero': 'X.Borg',
  'Base Damage': 53.46,
  'Base Attribute Damage': 39.57,
  'Unique Damage': 6.97,
  'Unique Attribute Damage': 0.0,
  'Extra Damage': 0.0,
  'Extra Attribute Damage': 0.0,
  'Sustained Damage': 0.0,
  'Sustained Attribute Damage': 0.0,
  'Passive Base Damage': 0.0,
  'Passive Attribute Damage': 0.0,
  'segment': 'Fighter'}]

colorGradient = [
                    "rgb(232 232 232 / 25%)",
                    "rgb(212 212 212 / 61%)",
                    "#9a9a9a",
                    "#707070",
                    "#454545",
                ]

st.radio(label="dummy", options=["Single", "Multi"], label_visibility="collapsed", horizontal=True, key="chart_sel")


# with st.columns([1,10,1])[1]:
if st.session_state["chart_sel"] == "Single":
    custom_circle_plot(
        plotData=data,
        dmgType=["Base Damage", "Unique Damage", "Extra Damage", "Sustained Damage", "Passive Damage"],
        colorGradient=colorGradient
    )
else:
    dmgTypeMulti = [
        ["Base Damage", "Base Attribute Damage"],
        ["Unique Damage", "Unique Attribute Damage"],
        ["Extra Damage", "Extra Attribute Damage"],
        ["Sustained Damage", "Sustained Attribute Damage"],
        ["Passive Damage", "Passive Attribute Damage"],
    ]
    categoryCol = ["rgb(232 232 232 / 25%)", "rgb(101 99 99 / 31%)"];
    chartLegend = ["Base", "Attribute"]
    custom_circle_plot(
        plotData=data_2,
        dmgType=["Base Damage", "Unique Damage", "Extra Damage", "Sustained Damage", "Passive Damage"],
        dmgTypeMulti=dmgTypeMulti, 
        colorGradient=categoryCol,
        chartLegend=chartLegend,
        singlePlot=False
    )