# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/couchbase_version.py
# at
#    2024-10-22 18:36:34.050486
__version__ = '4.3.3rc1'