from datetime import timezone

DEGREE_SIGN = u'\u2103'
RUN_LOOP_HOUR = 3600
MQTT_STATE=0
MQTT_MULTI_TOPIC_NODE = "raw"
MQTT_MESSAGE_EXPIRY_SECONDS = 7200                            # Expire after 2 hours, we will republish every hour if using version 5
SYSMON_VERSION = "1.2.11"

SENSOR_UID_STATUS = "status"
SENSOR_UID_SYSMON_VERSION = "sysmon_version"
SENSOR_UID_CPU = "cpu"
SENSOR_UID_TEMPERATURE = "temperature"
SENSOR_UID_MEMORY = "memory"
SENSOR_UID_MEMORY_USED = "memory_used_percent"
SENSOR_UID_MEMORY_BYTES_USED = "memory_used_bytes"
SENSOR_UID_MEMORY_BYTES_FREE = "memory_free_bytes"
SENSOR_UID_MEMORY_BYTES_TOTAL = "memory_total_bytes"
SENSOR_UID_ROOTFS = "rootfs_usage"
SENSOR_UID_LASTUPDATE = "lastupdate"
SENSOR_UID_PID_COUNT = "pid_count"
SENSOR_UID_CPU_COUNT = "cpu_count"
SENSOR_UID_CPU_FREQ = "cpu_frequency"
SENSOR_UID_CPU_AVG_1M = "cpu_average_1min"
SENSOR_UID_CPU_AVG_5M = "cpu_average_5min"
SENSOR_UID_CPU_AVG_15M = "cpu_average_15min"
SENSOR_UID_NET_BYTES_SENT = "network_bytes_sent"
SENSOR_UID_NET_BYTES_RECV = "network_bytes_received"
SENSOR_UID_NET_ERRORS_IN = "network_errors_in"
SENSOR_UID_NET_ERRORS_OUT = "network_errors_out"
SENSOR_UID_NET_DROPS_IN = "network_drops_in"
SENSOR_UID_NET_DROPS_OUT = "network_drops_out"
SENSOR_UID_NET_TOTAL_ERRORS_IN = "network_total_errors_in"
SENSOR_UID_NET_TOTAL_ERRORS_OUT = "network_total_errors_out"
SENSOR_UID_NET_TOTAL_DROPS_IN = "network_total_drops_in"
SENSOR_UID_NET_TOTAL_DROPS_OUT = "network_total_drops_out"

SENSOR_UID_OS_NAME = "os_name"
SENSOR_UID_OS_RELEASE = "os_release"
SENSOR_UID_OS_VERSION = "os_version"
SENSOR_UID_OS_ARCH = "os_architecture"

SENSOR_UID_LASTBOOTTIME = "lastboottime"
SENSOR_UID_VIP = "vip"
SENSOR_UID_NIC = "nic"

SENSOR_NAME_STATUS = "Status"
SENSOR_NAME_SYSMON_VERSION = "Sysmon Version"
SENSOR_NAME_CPU = "CPU"
SENSOR_NAME_TEMPERATURE = "Temperature"
SENSOR_NAME_MEMORY = "Memory"
SENSOR_NAME_MEMORY_USED = "Memory Used"
SENSOR_NAME_MEMORY_BYTES_USED = "Memory Used Bytes"
SENSOR_NAME_MEMORY_BYTES_FREE = "Memory Free Bytes"
SENSOR_NAME_MEMORY_BYTES_TOTAL = "Memory Total Bytes"
SENSOR_NAME_ROOTFS = "RootFS Usage"
SENSOR_NAME_LASTUPDATE = "Last Update"
SENSOR_NAME_PID_COUNT = "PID Count"
SENSOR_NAME_CPU_COUNT = "CPU Count"
SENSOR_NAME_CPU_FREQ = "CPU Frequency"
SENSOR_NAME_CPU_AVG_1M = "CPU Average Load Over 1 minute"
SENSOR_NAME_CPU_AVG_5M = "CPU Average Load Over 5 minutes"
SENSOR_NAME_CPU_AVG_15M = "CPU Average Load Over 15 minutes"
SENSOR_NAME_NET_BYTES_SENT = "Network Bytes Sent"
SENSOR_NAME_NET_BYTES_RECV = "Network Bytes Received"
SENSOR_NAME_NET_ERRORS_IN = "Network Input Errors"
SENSOR_NAME_NET_ERRORS_OUT = "Network Output Errors"
SENSOR_NAME_NET_DROPS_IN = "Network Input Drops"
SENSOR_NAME_NET_DROPS_OUT = "Network Output Drops"
SENSOR_NAME_NET_TOTAL_ERRORS_IN = "Network Total Input Errors"
SENSOR_NAME_NET_TOTAL_ERRORS_OUT = "Network Total Output Errors"
SENSOR_NAME_NET_TOTAL_DROPS_IN = "Network Total Input Drops"
SENSOR_NAME_NET_TOTAL_DROPS_OUT = "Network Total Output Drops"

SENSOR_NAME_OS_NAME = "OS Name"
SENSOR_NAME_OS_RELEASE = "OS Release"
SENSOR_NAME_OS_VERSION = "OS Version"
SENSOR_NAME_OS_ARCH = "OS Architecture"

SENSOR_NAME_LASTBOOTTIME = "Last Boot"
UTC = timezone.utc
