# coding: utf-8

"""
    public/portworx/pds/backup/apiv1/backup.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Platformiamv1SortByField(str, Enum):
    """
    Field names for sorting the list of IAMs.   - FIELD_UNSPECIFIED: Unspecified, do not use.  - EMAIL: Sorting based on the email of the iam.
    """

    """
    allowed enum values
    """
    FIELD_UNSPECIFIED = 'FIELD_UNSPECIFIED'
    EMAIL = 'EMAIL'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Platformiamv1SortByField from a JSON string"""
        return cls(json.loads(json_str))


