# coding: utf-8

"""
    public/portworx/pds/backup/apiv1/backup.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class V1AccountType(str, Enum):
    """
    Accepted account types.   - ACCOUNT_TYPE_UNSPECIFIED: Unspecified, do not use.  - FREEMIUM: Account is of freemium type for all three Portworx Service.  - ENTERPRISE: Account has a active subscription for at least one of the Portworx Services.
    """

    """
    allowed enum values
    """
    ACCOUNT_TYPE_UNSPECIFIED = 'ACCOUNT_TYPE_UNSPECIFIED'
    FREEMIUM = 'FREEMIUM'
    ENTERPRISE = 'ENTERPRISE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1AccountType from a JSON string"""
        return cls(json.loads(json_str))


