# coding: utf-8

"""
    public/portworx/pds/backup/apiv1/backup.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class V1DataServiceDeploymentTopologyStatusPhase(str, Enum):
    """
    Enum for Phase of the DataServiceDeployment Topology.   - PHASE_UNSPECIFIED: Unspecified status.  - IN_PROGRESS: In progress Status.  - PARTIAL_SUCCESS: Partial Success Status.  - SUCCESS: Successful Status.  - DELETE_PENDING: Delete is pending Status.  - DELETING: Delete in progress Status.  - FAILED: Failed Status.  - TIMED_OUT: Timed Out Status.
    """

    """
    allowed enum values
    """
    PHASE_UNSPECIFIED = 'PHASE_UNSPECIFIED'
    IN_PROGRESS = 'IN_PROGRESS'
    PARTIAL_SUCCESS = 'PARTIAL_SUCCESS'
    SUCCESS = 'SUCCESS'
    DELETE_PENDING = 'DELETE_PENDING'
    DELETING = 'DELETING'
    FAILED = 'FAILED'
    TIMED_OUT = 'TIMED_OUT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1DataServiceDeploymentTopologyStatusPhase from a JSON string"""
        return cls(json.loads(json_str))


