# coding: utf-8

"""
    public/portworx/pds/backup/apiv1/backup.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from portworxapis.models.v1_backup_policy1 import V1BackupPolicy1
from portworxapis.models.v1_page_based_pagination_response import V1PageBasedPaginationResponse
from typing import Optional, Set
from typing_extensions import Self

class V1ListBackupPoliciesResponse(BaseModel):
    """
    Response of list backup policies.
    """ # noqa: E501
    backup_policies: Optional[List[V1BackupPolicy1]] = Field(default=None, description="The list of backup policies scoped to a tenant.", alias="backupPolicies")
    pagination: Optional[V1PageBasedPaginationResponse] = None
    __properties: ClassVar[List[str]] = ["backupPolicies", "pagination"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1ListBackupPoliciesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in backup_policies (list)
        _items = []
        if self.backup_policies:
            for _item_backup_policies in self.backup_policies:
                if _item_backup_policies:
                    _items.append(_item_backup_policies.to_dict())
            _dict['backupPolicies'] = _items
        # override the default output from pydantic by calling `to_dict()` of pagination
        if self.pagination:
            _dict['pagination'] = self.pagination.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1ListBackupPoliciesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "backupPolicies": [V1BackupPolicy1.from_dict(_item) for _item in obj["backupPolicies"]] if obj.get("backupPolicies") is not None else None,
            "pagination": V1PageBasedPaginationResponse.from_dict(obj["pagination"]) if obj.get("pagination") is not None else None
        })
        return _obj


