# generated by datamodel-codegen:
#   filename:  secret_store_entry_state.json

from __future__ import annotations

from typing import Sequence

from typing_extensions import Literal, TypedDict


class SecretStoreEntryAcl1(TypedDict):
    type: Literal['UsersList']
    users: Sequence[str]


SecretStoreEntryAcl = SecretStoreEntryAcl1


class SecretStoreEntryState1(TypedDict):
    acl: SecretStoreEntryAcl
    version: Literal['V0']
    manifest_hash: str
    type: Literal['DatasetKey']


SecretStoreEntryState = SecretStoreEntryState1
