# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from .teams import (
    TeamsResource,
    AsyncTeamsResource,
    TeamsResourceWithRawResponse,
    AsyncTeamsResourceWithRawResponse,
    TeamsResourceWithStreamingResponse,
    AsyncTeamsResourceWithStreamingResponse,
)
from .states import (
    StatesResource,
    AsyncStatesResource,
    StatesResourceWithRawResponse,
    AsyncStatesResourceWithRawResponse,
    StatesResourceWithStreamingResponse,
    AsyncStatesResourceWithStreamingResponse,
)
from .leagues import (
    LeaguesResource,
    AsyncLeaguesResource,
    LeaguesResourceWithRawResponse,
    AsyncLeaguesResourceWithRawResponse,
    LeaguesResourceWithStreamingResponse,
    AsyncLeaguesResourceWithStreamingResponse,
)
from .players import (
    PlayersResource,
    AsyncPlayersResource,
    PlayersResourceWithRawResponse,
    AsyncPlayersResourceWithRawResponse,
    PlayersResourceWithStreamingResponse,
    AsyncPlayersResourceWithStreamingResponse,
)
from .seasons import (
    SeasonsResource,
    AsyncSeasonsResource,
    SeasonsResourceWithRawResponse,
    AsyncSeasonsResourceWithRawResponse,
    SeasonsResourceWithStreamingResponse,
    AsyncSeasonsResourceWithStreamingResponse,
)
from .fixtures import (
    FixturesResource,
    AsyncFixturesResource,
    FixturesResourceWithRawResponse,
    AsyncFixturesResourceWithRawResponse,
    FixturesResourceWithStreamingResponse,
    AsyncFixturesResourceWithStreamingResponse,
)
from .football import (
    FootballResource,
    AsyncFootballResource,
    FootballResourceWithRawResponse,
    AsyncFootballResourceWithRawResponse,
    FootballResourceWithStreamingResponse,
    AsyncFootballResourceWithStreamingResponse,
)
from .standings import (
    StandingsResource,
    AsyncStandingsResource,
    StandingsResourceWithRawResponse,
    AsyncStandingsResourceWithRawResponse,
    StandingsResourceWithStreamingResponse,
    AsyncStandingsResourceWithStreamingResponse,
)
from .livescores import (
    LivescoresResource,
    AsyncLivescoresResource,
    LivescoresResourceWithRawResponse,
    AsyncLivescoresResourceWithRawResponse,
    LivescoresResourceWithStreamingResponse,
    AsyncLivescoresResourceWithStreamingResponse,
)
from .topscorers import (
    TopscorersResource,
    AsyncTopscorersResource,
    TopscorersResourceWithRawResponse,
    AsyncTopscorersResourceWithRawResponse,
    TopscorersResourceWithStreamingResponse,
    AsyncTopscorersResourceWithStreamingResponse,
)

__all__ = [
    "LeaguesResource",
    "AsyncLeaguesResource",
    "LeaguesResourceWithRawResponse",
    "AsyncLeaguesResourceWithRawResponse",
    "LeaguesResourceWithStreamingResponse",
    "AsyncLeaguesResourceWithStreamingResponse",
    "FixturesResource",
    "AsyncFixturesResource",
    "FixturesResourceWithRawResponse",
    "AsyncFixturesResourceWithRawResponse",
    "FixturesResourceWithStreamingResponse",
    "AsyncFixturesResourceWithStreamingResponse",
    "TeamsResource",
    "AsyncTeamsResource",
    "TeamsResourceWithRawResponse",
    "AsyncTeamsResourceWithRawResponse",
    "TeamsResourceWithStreamingResponse",
    "AsyncTeamsResourceWithStreamingResponse",
    "StandingsResource",
    "AsyncStandingsResource",
    "StandingsResourceWithRawResponse",
    "AsyncStandingsResourceWithRawResponse",
    "StandingsResourceWithStreamingResponse",
    "AsyncStandingsResourceWithStreamingResponse",
    "PlayersResource",
    "AsyncPlayersResource",
    "PlayersResourceWithRawResponse",
    "AsyncPlayersResourceWithRawResponse",
    "PlayersResourceWithStreamingResponse",
    "AsyncPlayersResourceWithStreamingResponse",
    "LivescoresResource",
    "AsyncLivescoresResource",
    "LivescoresResourceWithRawResponse",
    "AsyncLivescoresResourceWithRawResponse",
    "LivescoresResourceWithStreamingResponse",
    "AsyncLivescoresResourceWithStreamingResponse",
    "SeasonsResource",
    "AsyncSeasonsResource",
    "SeasonsResourceWithRawResponse",
    "AsyncSeasonsResourceWithRawResponse",
    "SeasonsResourceWithStreamingResponse",
    "AsyncSeasonsResourceWithStreamingResponse",
    "TopscorersResource",
    "AsyncTopscorersResource",
    "TopscorersResourceWithRawResponse",
    "AsyncTopscorersResourceWithRawResponse",
    "TopscorersResourceWithStreamingResponse",
    "AsyncTopscorersResourceWithStreamingResponse",
    "StatesResource",
    "AsyncStatesResource",
    "StatesResourceWithRawResponse",
    "AsyncStatesResourceWithRawResponse",
    "StatesResourceWithStreamingResponse",
    "AsyncStatesResourceWithStreamingResponse",
    "FootballResource",
    "AsyncFootballResource",
    "FootballResourceWithRawResponse",
    "AsyncFootballResourceWithRawResponse",
    "FootballResourceWithStreamingResponse",
    "AsyncFootballResourceWithStreamingResponse",
]
