PERMS = {
    "notification": {
        "edit.notification": "edit.notification",
        "view.notification": "view.notification",
        "delete.notification": "delete.notification",
    },
    "treasury": {
        "list_treasury_files": "list_treasury_files",
        "admin_treasury": "admin_treasury",
        "view.treasury": "view.treasury",
    },
    "timeslot": {"view.timeslot": "view.timeslot"},
    "sale_products": {"list.sale_products": "list.sale_products"},
    "sale_product_category": {
        "view.sale_product_category": "view.sale_product_category",
        "delete.sale_product_category": "delete.sale_product_category",
        "edit.sale_product_category": "edit.sale_product_category",
        "add.sale_product_category": "add.sale_product_category",
    },
    "indicator": {
        "valid.indicator": "valid.indicator",
        "force.indicator": "force.indicator",
        "view.indicator": "view.indicator",
    },
    "training_product": {
        "list.training_product": "list.training_product",
        "edit.training_product": "edit.training_product",
        "add.training_product": "add.training_product",
    },
    "userdatas": {
        "doctypes.userdatas": "doctypes.userdatas",
        "admin.userdatas": "admin.userdatas",
        "addfile.userdatas": "addfile.userdatas",
        "view.userdatas": "view.userdatas",
        "py3o.userdatas": "py3o.userdatas",
        "history.userdatas": "history.userdatas",
        "edit.userdatas": "edit.userdatas",
        "filelist.userdatas": "filelist.userdatas",
        "add.userdatas": "add.userdatas",
        "delete.userdatas": "delete.userdatas",
    },
    "estimations": {
        "list.estimations": "list.estimations",
        "list_estimations": "list_estimations",
        "admin.estimations": "admin.estimations",
    },
    "supplier_order": {
        "draft.supplier_order": "draft.supplier_order",
        "edit.supplier_order": "edit.supplier_order",
        "list.supplier_order": "list.supplier_order",
        "wait.supplier_order": "wait.supplier_order",
        "view.supplier_order": "view.supplier_order",
        "add.supplier_order": "add.supplier_order",
        "valid.supplier_order": "valid.supplier_order",
        "invalid.supplier_order": "invalid.supplier_order",
        "duplicate.supplier_order": "duplicate.supplier_order",
        "delete.supplier_order": "delete.supplier_order",
        "admin.supplier_order": "admin.supplier_order",
    },
    "estimation": {
        "delete.estimation": "delete.estimation",
        "geninv.estimation": "geninv.estimation",
        "invalid.estimation": "invalid.estimation",
        "list.estimation": "list.estimation",
        "valid.estimation": "valid.estimation",
        "edit.estimation": "edit.estimation",
        "draft.estimation": "draft.estimation",
        "duplicate.estimation": "duplicate.estimation",
        "add.estimation": "add.estimation",
        "wait.estimation": "wait.estimation",
        "gen_supplier_order.estimation": "gen_supplier_order.estimation",
        "admin.estimation": "admin.estimation",
        "view.estimation": "view.estimation",
        "set_date.estimation": "set_date.estimation",
        "set_signed_status.estimation": "set_signed_status.estimation",
        "genbusiness.estimation": "genbusiness.estimation",
    },
    "supplier": {
        "edit_supplier": "edit_supplier",
        "view_supplier": "view_supplier",
        "delete_supplier": "delete_supplier",
        "add_supplier": "add_supplier",
    },
    "invoice": {
        "draft.invoice": "draft.invoice",
        "request_urssaf3p.invoice": "request_urssaf3p.invoice",
        "duplicate.invoice": "duplicate.invoice",
        "edit.invoice": "edit.invoice",
        "set_date.invoice": "set_date.invoice",
        "gencinv.invoice": "gencinv.invoice",
        "invalid.invoice": "invalid.invoice",
        "gen_supplier_invoice.invoice": "gen_supplier_invoice.invoice",
        "view.invoice": "view.invoice",
        "delete.invoice": "delete.invoice",
        "add.invoice": "add.invoice",
        "admin.invoice": "admin.invoice",
        "valid.invoice": "valid.invoice",
        "wait.invoice": "wait.invoice",
        "set_treasury.invoice": "set_treasury.invoice",
        "add_payment.invoice": "add_payment.invoice",
    },
    "expensesheet": {
        "view.expensesheet": "view.expensesheet",
        "add.expensesheet": "add.expensesheet",
        "admin.expensesheet": "admin.expensesheet",
        "set_justified.expensesheet": "set_justified.expensesheet",
        "duplicate.expensesheet": "duplicate.expensesheet",
        "set_treasury.expensesheet": "set_treasury.expensesheet",
        "invalid.expensesheet": "invalid.expensesheet",
        "draft.expensesheet": "draft.expensesheet",
        "valid.expensesheet": "valid.expensesheet",
        "delete.expensesheet": "delete.expensesheet",
        "wait.expensesheet": "wait.expensesheet",
        "add_payment.expensesheet": "add_payment.expensesheet",
        "edit.expensesheet": "edit.expensesheet",
    },
    "cancelinvoice": {
        "edit.cancelinvoice": "edit.cancelinvoice",
        "set_treasury.cancelinvoice": "set_treasury.cancelinvoice",
        "wait.cancelinvoice": "wait.cancelinvoice",
        "view.cancelinvoice": "view.cancelinvoice",
        "duplicate.cancelinvoice": "duplicate.cancelinvoice",
        "valid.cancelinvoice": "valid.cancelinvoice",
        "invalid.cancelinvoice": "invalid.cancelinvoice",
        "delete.cancelinvoice": "delete.cancelinvoice",
        "admin.cancelinvoice": "admin.cancelinvoice",
        "set_date.cancelinvoice": "set_date.cancelinvoice",
        "draft.cancelinvoice": "draft.cancelinvoice",
    },
    "customer": {
        "view_customer": "view_customer",
        "add_customer": "add_customer",
        "delete_customer": "delete_customer",
        "edit_customer": "edit_customer",
    },
    "commercial": {
        "view.commercial": "view.commercial",
        "edit_commercial_handling": "edit_commercial_handling",
    },
    "trainerdatas": {
        "edit.trainerdatas": "edit.trainerdatas",
        "add.trainerdatas": "add.trainerdatas",
        "delete.trainerdatas": "delete.trainerdatas",
        "view.trainerdatas": "view.trainerdatas",
        "filelist.trainerdatas": "filelist.trainerdatas",
        "admin.trainerdatas": "admin.trainerdatas",
        "addfile.trainerdatas": "addfile.trainerdatas",
        "disable.trainerdatas": "disable.trainerdatas",
    },
    "plan": {"edit.plan": "edit.plan", "view.plan": "view.plan"},
    "login": {
        "admin.login": "admin.login",
        "edit.login": "edit.login",
        "view.login": "view.login",
        "add.login": "add.login",
        "disable.login": "disable.login",
        "delete.login": "delete.login",
        "set_password.login": "set_password.login",
    },
    "price_studies": {"list.price_studies": "list.price_studies"},
    "event": {
        "signup.event": "signup.event",
        "edit_owner.event": "edit_owner.event",
        "signout.event": "signout.event",
    },
    "business": {
        "view.business": "view.business",
        "close.business": "close.business",
        "list.business": "list.business",
        "delete.business": "delete.business",
        "edit.business": "edit.business",
        "py3o.business": "py3o.business",
    },
    "supplier_invoice": {
        "view.supplier_invoice": "view.supplier_invoice",
        "add_payment.supplier_invoice": "add_payment.supplier_invoice",
        "valid.supplier_invoice": "valid.supplier_invoice",
        "invalid.supplier_invoice": "invalid.supplier_invoice",
        "draft.supplier_invoice": "draft.supplier_invoice",
        "set_types.supplier_invoice": "set_types.supplier_invoice",
        "delete.supplier_invoice": "delete.supplier_invoice",
        "wait.supplier_invoice": "wait.supplier_invoice",
        "edit.supplier_invoice": "edit.supplier_invoice",
        "list.supplier_invoice": "list.supplier_invoice",
        "duplicate.supplier_invoice": "duplicate.supplier_invoice",
        "add.supplier_invoice": "add.supplier_invoice",
        "admin.supplier_invoice": "admin.supplier_invoice",
    },
    "business_invoice": {"add.business_invoice": "add.business_invoice"},
    "statuslogentry": {
        "edit.statuslogentry": "edit.statuslogentry",
        "delete.statuslogentry": "delete.statuslogentry",
        "view.statuslogentry": "view.statuslogentry",
    },
    "work_item": {
        "add.work_item": "add.work_item",
        "view.work_item": "view.work_item",
        "delete.work_item": "delete.work_item",
        "edit.work_item": "edit.work_item",
    },
    "phase": {
        "add_phase": "add_phase",
        "add.phase": "add.phase",
        "edit.phase": "edit.phase",
        "edit_phase": "edit_phase",
        "delete.phase": "delete.phase",
    },
    "project": {
        "edit_project": "edit_project",
        "edit.project": "edit.project",
        "view_project": "view_project",
        "add.project": "add.project",
        "admin.project": "admin.project",
        "view.project": "view.project",
        "add_project": "add_project",
    },
    "file": {
        "add.file": "add.file",
        "view.file": "view.file",
        "delete.file": "delete.file",
        "edit.file": "edit.file",
    },
    "holiday": {"add.holiday": "add.holiday", "edit.holiday": "edit.holiday"},
    "price_study": {
        "add.price_study": "add.price_study",
        "edit.price_study": "edit.price_study",
        "view.price_study": "view.price_study",
    },
    "workshop": {
        "admin.workshop": "admin.workshop",
        "edit.workshop": "edit.workshop",
        "list.workshop": "list.workshop",
        "view.workshop": "view.workshop",
        "add.workshop": "add.workshop",
    },
    "user": {
        "delete.user": "delete.user",
        "view.user": "view.user",
        "edit.user": "edit.user",
        "admin.user": "admin.user",
        "set_email.user": "set_email.user",
    },
    "sale_product": {
        "edit.sale_product": "edit.sale_product",
        "add.sale_product": "add.sale_product",
        "view.sale_product": "view.sale_product",
        "delete.sale_product": "delete.sale_product",
    },
    "company": {
        "edit_company": "edit_company",
        "list.company": "list.company",
        "admin_company": "admin_company",
        "view.company": "view.company",
        "admin.company": "admin.company",
    },
    "customers": {"list_customers": "list_customers"},
    "construction": {
        "list.construction": "list.construction",
        "add.construction": "add.construction",
    },
    "business_payment_deadline": {
        "edit.business_payment_deadline.invoice_id": "edit.business_payment_deadline.invoice_id",
        "edit.business_payment_deadline": "edit.business_payment_deadline",
        "delete.business_payment_deadline": "delete.business_payment_deadline",
        "edit.business_payment_deadline.amount": "edit.business_payment_deadline.amount",
        "edit.business_payment_deadline.date": "edit.business_payment_deadline.date",
    },
    "admin": {"addgroup.admin": "addgroup.admin"},
    "suppliers": {"list_suppliers": "list_suppliers"},
    "activity": {
        "add.activity": "add.activity",
        "view.activity": "view.activity",
        "admin.activity": "admin.activity",
        "edit.activity": "edit.activity",
        "list.activity": "list.activity",
    },
    "expenses": {"list_expenses": "list_expenses"},
    "training": {"admin.training": "admin.training", "list.training": "list.training"},
    "sale_product_categories": {
        "list.sale_product_categories": "list.sale_product_categories"
    },
    "stock_operation": {
        "view.stock_operation": "view.stock_operation",
        "edit.stock_operation": "edit.stock_operation",
        "add.stock_operation": "add.stock_operation",
        "delete.stock_operation": "delete.stock_operation",
    },
    "holidays": {"list.holidays": "list.holidays"},
    "work_items": {"list.work_items": "list.work_items"},
    "invoices": {
        "list_invoices": "list_invoices",
        "list.invoices": "list.invoices",
        "admin.invoices": "admin.invoices",
    },
    "competence": {
        "edit_competence": "edit_competence",
        "view_competence": "view_competence",
    },
    "expense": {"add.expense": "add.expense"},
    "competences": {"list_competences": "list_competences"},
    "projects": {"list_projects": "list_projects"},
    "stock_operations": {"list.stock_operations": "list.stock_operations"},
    "businesses": {"list.businesses": "list.businesses"},
    "bpf": {"edit.bpf": "edit.bpf"},
    "accounting": {"view.accounting": "view.accounting"},
    "node": {"view.node": "view.node"},
    "files": {"list.files": "list.files"},
}
