import numpy as np
from .struct_mask_parameters import StructMaskParameters as StructMaskParameters

def uniform_manipulate(patch: np.ndarray, mask_pixel_percentage: float, subpatch_size: int = 11, remove_center: bool = True, struct_params: StructMaskParameters | None = None, rng: np.random.Generator | None = None) -> tuple[np.ndarray, np.ndarray]: ...
def median_manipulate(patch: np.ndarray, mask_pixel_percentage: float, subpatch_size: int = 11, struct_params: StructMaskParameters | None = None, rng: np.random.Generator | None = None) -> tuple[np.ndarray, np.ndarray]: ...
