'''
## This file is autogenerated from macrosynergy setup.py.

It contains version information for the macrosynergy package.

short_version: 0.1.36

version: 0.1.36

full_version: 0.1.36

git_revision: 9db418fb41aa2e24feacf14d7930d1b8b6166177

release: True

'''
short_version: str = '0.1.36'
version: str = '0.1.36'
full_version: str = '0.1.36'
git_revision: str = '9db418fb41aa2e24feacf14d7930d1b8b6166177'
release: bool = True
if not release:
    version = full_version
