
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-18T16:33:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "19a31281c59d5cd21eeb0e2cb0ef796dc54283b6",
 "version": "0.78"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
