# coding: utf-8

"""
    public/portworx/pds/backup/apiv1/backup.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ConfigBackupType(str, Enum):
    """
    Enum for Backup Type of the backup configuration.   - BACKUP_TYPE_UNSPECIFIED: Unspecified type.  - ADHOC: Adhoc Backup.  - SCHEDULED: Scheduled Backup.
    """

    """
    allowed enum values
    """
    BACKUP_TYPE_UNSPECIFIED = 'BACKUP_TYPE_UNSPECIFIED'
    ADHOC = 'ADHOC'
    SCHEDULED = 'SCHEDULED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConfigBackupType from a JSON string"""
        return cls(json.loads(json_str))


