def check_axes_validity(axes: str) -> None: ...
def value_ge_than_8_power_of_2(value: int) -> None: ...
def patch_size_ge_than_8_power_of_2(patch_list: list[int] | tuple[int, ...] | None) -> None: ...
