# coding: utf-8

"""
    Search API

    API for search and recommendation services.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_query_get200_response_inner import ApiQueryGet200ResponseInner

class TestApiQueryGet200ResponseInner(unittest.TestCase):
    """ApiQueryGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiQueryGet200ResponseInner:
        """Test ApiQueryGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiQueryGet200ResponseInner`
        """
        model = ApiQueryGet200ResponseInner()
        if include_optional:
            return ApiQueryGet200ResponseInner(
                product_id = '',
                product_url_y = '',
                product_name_y = '',
                product_description_y = '',
                product_images_y = [
                    ''
                    ],
                keyword_score = 1.337,
                combined_score = 1.337,
                cross_encoder_score = 1.337,
                product_price_y = 1.337
            )
        else:
            return ApiQueryGet200ResponseInner(
        )
        """

    def testApiQueryGet200ResponseInner(self):
        """Test ApiQueryGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
