# coding: utf-8

"""
    public/portworx/pds/metric/apiv1/metric.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from portworx.models.v1_data_service_deployment_meta_data import V1DataServiceDeploymentMetaData
from portworx.models.v1_phase1 import V1Phase1
from typing import Optional, Set
from typing_extensions import Self

class Backupconfigv1Status(BaseModel):
    """
    Status for backup configuration.
    """ # noqa: E501
    phase: Optional[V1Phase1] = V1Phase1.PHASE_UNSPECIFIED
    custom_resource_name: Optional[StrictStr] = Field(default=None, description="Custom Resource Name is the kubernetes resource name for the backup that is built from ID.", alias="customResourceName")
    is_backup_policy_synchronized: Optional[StrictBool] = Field(default=None, description="Flag to check if the backup policy is synchronized or not.", alias="isBackupPolicySynchronized")
    data_service_deployment_meta_data: Optional[V1DataServiceDeploymentMetaData] = Field(default=None, alias="dataServiceDeploymentMetaData")
    error_code: Optional[StrictStr] = Field(default=None, description="Error code.", alias="errorCode")
    error_message: Optional[StrictStr] = Field(default=None, description="Error message.", alias="errorMessage")
    __properties: ClassVar[List[str]] = ["phase", "customResourceName", "isBackupPolicySynchronized", "dataServiceDeploymentMetaData", "errorCode", "errorMessage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Backupconfigv1Status from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data_service_deployment_meta_data
        if self.data_service_deployment_meta_data:
            _dict['dataServiceDeploymentMetaData'] = self.data_service_deployment_meta_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Backupconfigv1Status from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "phase": obj.get("phase") if obj.get("phase") is not None else V1Phase1.PHASE_UNSPECIFIED,
            "customResourceName": obj.get("customResourceName"),
            "isBackupPolicySynchronized": obj.get("isBackupPolicySynchronized"),
            "dataServiceDeploymentMetaData": V1DataServiceDeploymentMetaData.from_dict(obj["dataServiceDeploymentMetaData"]) if obj.get("dataServiceDeploymentMetaData") is not None else None,
            "errorCode": obj.get("errorCode"),
            "errorMessage": obj.get("errorMessage")
        })
        return _obj


