# coding: utf-8

"""
    public/portworx/pds/metric/apiv1/metric.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class V1InfraResourceType(str, Enum):
    """
    Type of the resource.   - TYPE_UNSPECIFIED: Unspecified, do not use.  - ACCOUNT: Currently supported infra resources. Infra resource of type account.  - TENANT: Infra resource of type tenant.  - PROJECT: Infra resource of type projects.  - TARGET_CLUSTER: Infra resource target cluster.  - NAMESPACE: Infra resource of type namespace.  - CREDENTIAL: Infra resource of type credential.  - BACKUP_LOCATION: Infra resource of type backup location.  - BACKUP_POLICY: Infra resource of type backup policy.  - TEMPLATE: Infra resource of type template.  - INVITATION: Infra resource of type invitation.
    """

    """
    allowed enum values
    """
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    ACCOUNT = 'ACCOUNT'
    TENANT = 'TENANT'
    PROJECT = 'PROJECT'
    TARGET_CLUSTER = 'TARGET_CLUSTER'
    NAMESPACE = 'NAMESPACE'
    CREDENTIAL = 'CREDENTIAL'
    BACKUP_LOCATION = 'BACKUP_LOCATION'
    BACKUP_POLICY = 'BACKUP_POLICY'
    TEMPLATE = 'TEMPLATE'
    INVITATION = 'INVITATION'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1InfraResourceType from a JSON string"""
        return cls(json.loads(json_str))


