# coding: utf-8

"""
    public/portworx/pds/metric/apiv1/metric.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class V1KubePlatformType(str, Enum):
    """
    kubeplatform values.   - TYPE_UNSPECIFIED: Unsepecified.  - AWS: Aws platform.  - AZURE: Azure platform.  - OCP: Openshift cloud platform.  - GCP: Google cloud platform.  - VSPHERE: VMware vSphere.  - UNKNOWN: Unknown platform.
    """

    """
    allowed enum values
    """
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    AWS = 'AWS'
    AZURE = 'AZURE'
    OCP = 'OCP'
    GCP = 'GCP'
    VSPHERE = 'VSPHERE'
    UNKNOWN = 'UNKNOWN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1KubePlatformType from a JSON string"""
        return cls(json.loads(json_str))


