# coding: utf-8

"""
    public/portworx/pds/metric/apiv1/metric.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class V1PhaseType1(str, Enum):
    """
    Type of phase the project is in currently should be one of the below.   - TYPE_UNSPECIFIED: Unspecified, do not use.  - ACTIVE: The project is in use and active.  - DELETE_PENDING: Deletion of project has not started.  - DELETE_IN_PROGRESS: Deletion of the project is scheduled and in progress.
    """

    """
    allowed enum values
    """
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    ACTIVE = 'ACTIVE'
    DELETE_PENDING = 'DELETE_PENDING'
    DELETE_IN_PROGRESS = 'DELETE_IN_PROGRESS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1PhaseType1 from a JSON string"""
        return cls(json.loads(json_str))


