# trunk-ignore(ruff/B018)
{
    "name": "HR Attendance Mitxelena",
    "license": "AGPL-3",
    "version": "14.0.1.0.56",
    "category": "Human Resources",
    "sequence": 20,
    "summary": "Employee Attendances Customizations for Mitxelena",
    "website": "https://git.coopdevs.org/coopdevs/odoo/odoo-addons/odoo-mitxelena",
    "author": "Coopdevs Treball SCCL",
    "depends": [
        "base",
        "base_automation",
        "hr",
        "hr_attendance",
        "hr_attendance_validation",
        "hr_entry_type_mitxelena",
    ],
    "data": [
        "data/assets.xml",
        "data/hr_attendance_scheduled_action.xml",
        "data/hr_attendance_server_action.xml",
        "data/hr_attendance_system_parameters.xml",
        "data/resource_calendar_cron.xml",
        "data/resource_calendar_data.xml",
        "data/resource_calendar_attendances_data.xml",
        "data/hr_validation_cron.xml",
        "reports/hr_attendance_validation_report.xml",
        "reports/hr_attendance_validation_report_template.xml",
        "reports/hr_attendance_validation_report_sub_templates.xml",
        "security/ir.model.access.csv",
        "views/hr_attendance_validation_views.xml",
        "views/hr_attendance_views.xml",
        "views/hr_employee_views.xml",
        "views/resource_calendar_views.xml",
        "views/reset.xml",
        "wizards/hr_leave_modification_wizard_view.xml",
    ],
    "qweb": [
        "static/src/xml/attendance.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
