# Generated by Django 3.2.14 on 2022-07-15 22:32

import wall_e_models.customFields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wall_e_models', '0004_auto_20220206_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banrecords',
            name='ban_id',
            field=wall_e_models.customFields.GeneratedIdentityField(primary_key=True, serialize=False),
        ),
    ]
