# Generated by Django 3.2.20 on 2023-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0008_rename_banrecords_banrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.BigIntegerField()),
                ('channel_name', models.CharField(default=None, max_length=500, null=True)),
                ('channel_id', models.BigIntegerField()),
                ('help_message_expiration_date', models.BigIntegerField(default=0)),
                ('time_created', models.BigIntegerField(default=0)),
            ],
        ),
    ]
