# Generated by Django 3.2.20 on 2023-10-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0009_helpmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_discord_url', models.CharField(max_length=5000)),
                ('avatar_discord_permanent_url', models.CharField(max_length=5000)),
            ],
        ),
    ]
