# Generated by Django 3.2.20 on 2023-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0011_auto_20231109_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoint',
            name='deleted_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpoint',
            name='leveling_update_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpoint',
            name='leveling_update_needed',
            field=models.BooleanField(default=True),
        ),
    ]
