# Generated by Django 3.2.23 on 2023-11-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0017_auto_20231117_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBucketInProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_number_completed', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userpoint',
            name='bucket_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='userpoint',
            name='date_to_check',
        )
    ]
