# Generated by Django 3.2.20 on 2024-01-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0018_auto_20231118_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banrecord',
            old_name='ban_date',
            new_name='epoch_ban_date',
        ),
        migrations.RenameField(
            model_name='banrecord',
            old_name='unban_date',
            new_name='epoch_unban_date',
        ),
        migrations.AddField(
            model_name='banrecord',
            name='is_purged',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banrecord',
            name='purge_window_days',
            field=models.IntegerField(default=1),
        ),
    ]
