import torch

def mse_loss(source: torch.Tensor, target: torch.Tensor) -> torch.Tensor: ...
def n2v_loss(manipulated_patches: torch.Tensor, original_patches: torch.Tensor, masks: torch.Tensor) -> torch.Tensor: ...
def mae_loss(samples: torch.Tensor, labels: torch.Tensor) -> torch.Tensor: ...
