# coding: utf-8

"""
    public/portworx/pds/metric/apiv1/metric.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class V1Config10(BaseModel):
    """
    Config provides configuration data of the template instance.
    """ # noqa: E501
    kind: Optional[StrictStr] = Field(default=None, description="Kind to the template instance used to identify the template schema.")
    semantic_version: Optional[StrictStr] = Field(default=None, description="Semantic version of the template used to identify template schema. and latest revision for the given template instance kind.", alias="semanticVersion")
    revision_uid: Optional[StrictStr] = Field(default=None, description="Uid of the schema used to create the template instance.", alias="revisionUid")
    template_values: Optional[Dict[str, Any]] = Field(default=None, description="Key, value pairs of the template instance.", alias="templateValues")
    __properties: ClassVar[List[str]] = ["kind", "semanticVersion", "revisionUid", "templateValues"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1Config10 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1Config10 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kind": obj.get("kind"),
            "semanticVersion": obj.get("semanticVersion"),
            "revisionUid": obj.get("revisionUid"),
            "templateValues": obj.get("templateValues")
        })
        return _obj


