# coding: utf-8

"""
    public/portworx/pds/metric/apiv1/metric.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class V1Phase(str, Enum):
    """
    Enum for phase of the restore.   - PHASE_UNSPECIFIED: Phase is unspecified.  - INITIALIZING: Restore is initializing.  - PENDING: Restore has not yet started.  - RESTORING_CLOUDSNAP: Waiting for the cloud snap restore to complete.  - RESTORING_DATA_SERVICE_DEPLOYMENT_CR: PV and PVC resources are ready and we're waiting to get the data service deployment manifest from the backup.  - RESTORING_DATA_SERVICE_DEPLOYMENT: New data service deployment has been created and we're waiting for the restore process to complete.  - DATA_SERVICE_DEPLOYMENT_ENTERING_NORMAL_MODE: Restore process in data service deployment has succeeded and we're waiting until it becomes healthy in normal mode.  - SUCCESSFUL: Restore successful.  - FAILED: Restore failed.
    """

    """
    allowed enum values
    """
    PHASE_UNSPECIFIED = 'PHASE_UNSPECIFIED'
    INITIALIZING = 'INITIALIZING'
    PENDING = 'PENDING'
    RESTORING_CLOUDSNAP = 'RESTORING_CLOUDSNAP'
    RESTORING_DATA_SERVICE_DEPLOYMENT_CR = 'RESTORING_DATA_SERVICE_DEPLOYMENT_CR'
    RESTORING_DATA_SERVICE_DEPLOYMENT = 'RESTORING_DATA_SERVICE_DEPLOYMENT'
    DATA_SERVICE_DEPLOYMENT_ENTERING_NORMAL_MODE = 'DATA_SERVICE_DEPLOYMENT_ENTERING_NORMAL_MODE'
    SUCCESSFUL = 'SUCCESSFUL'
    FAILED = 'FAILED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1Phase from a JSON string"""
        return cls(json.loads(json_str))


