# coding: utf-8

"""
    Quay Frontend

    This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@quay.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import quayio_sdk
from quayio_sdk.models.new_prototype_activating_user import NewPrototypeActivatingUser  # noqa: E501
from quayio_sdk.rest import ApiException


class TestNewPrototypeActivatingUser(unittest.TestCase):
    """NewPrototypeActivatingUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewPrototypeActivatingUser(self):
        """Test NewPrototypeActivatingUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = quayio_sdk.models.new_prototype_activating_user.NewPrototypeActivatingUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
