
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-18T12:46:30-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c89d77a82e2ef7772c26f6cd10cd4b101ce3f90d",
 "version": "2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
