from pytorch_lightning import LightningModule as LightningModule, Trainer as Trainer
from pytorch_lightning.callbacks import TQDMProgressBar
from tqdm import tqdm

class ProgressBarCallback(TQDMProgressBar):
    def init_train_tqdm(self) -> tqdm: ...
    def init_validation_tqdm(self) -> tqdm: ...
    def init_test_tqdm(self) -> tqdm: ...
    def get_metrics(self, trainer: Trainer, pl_module: LightningModule) -> dict[str, int | str | float | dict[str, float]]: ...
