


__version__ = "0.1.2"

PYMODULE_VERSION = __version__

CORE_VERSION = "0.0.1"
PLATFORM_VERSION = "0.0.1"
SCALARS_VERSION = "0.0.9"
INTERVALS_VERSION = "0.0.1"
ALGEBRA_VERSION = "0.0.1"
STREAMS_VERSION = "0.0.1"
