"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .googleproduct import GoogleProduct, GoogleProductTypedDict
from exfunc_sdk import utils
from exfunc_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GetProductDetailsRequestBodyTypedDict(TypedDict):
    product_id: str
    r"""The ID of the product to retrieve"""
    country_code: NotRequired[str]
    r"""The country code for the product details"""


class GetProductDetailsRequestBody(BaseModel):
    product_id: str
    r"""The ID of the product to retrieve"""

    country_code: Optional[str] = None
    r"""The country code for the product details"""


class GetProductDetailsGoogleResponseResponseBodyData(BaseModel):
    message: Optional[str] = None
    r"""Error message string"""


class GetProductDetailsGoogleResponseResponseBody(Exception):
    r"""GetProductDetails API server error response"""

    data: GetProductDetailsGoogleResponseResponseBodyData

    def __init__(self, data: GetProductDetailsGoogleResponseResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, GetProductDetailsGoogleResponseResponseBodyData
        )


class GetProductDetailsGoogleResponseBodyData(BaseModel):
    message: Optional[str] = None
    r"""Error message string"""


class GetProductDetailsGoogleResponseBody(Exception):
    r"""GetProductDetails API user error response"""

    data: GetProductDetailsGoogleResponseBodyData

    def __init__(self, data: GetProductDetailsGoogleResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, GetProductDetailsGoogleResponseBodyData)


class GetProductDetailsResponseBodyTypedDict(TypedDict):
    r"""GetProductDetails API successful response"""

    product: NotRequired[GoogleProductTypedDict]


class GetProductDetailsResponseBody(BaseModel):
    r"""GetProductDetails API successful response"""

    product: Optional[GoogleProduct] = None
