
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-22T14:14:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd2d5e921569c76eb65b04575850136e095291aa",
 "version": "2.9.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
