
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-22T11:29:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb30d2a11593451dbc5d2e066c1d887c9b7c67f1",
 "version": "1.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
